name: Algolia Indexer

on:
  push:
    branches: main

jobs:
  algolia_indexer:
    runs-on: ubuntu-latest
    env:
      APPLICATION_ID: 'UJCTEGEXU7'
      API_KEY: ${{ secrets.API_KEY_WITH_WRITE_PERMISSIONS }}
      INDEX_NAME: 'karais89.github.io' # example.com
      CONFIG: ${{ secrets.CONFIG }}
    name: Index Algolia
    steps:
    - name: Algolia Docsearch Action
      id: algolia
      uses:  adapttive/algolia-docsearch-action@1.1.1